### ISSUE TITLE
Screen broadcasting with both, the vanilla discord app and enmity won't work

### ISSUE THREAD

**Issue by toastylol** [enmity-mod/enmity#28]
Apparently, if you have both enmity and discord installed, screen broadcasting just stops working altogether for both apps. Both apps show up on the menu where you select the app you want to broadcast/screen record with both neither work. 
![image](https://user-images.githubusercontent.com/115657726/195411005-aa1f2ce5-4811-446e-a718-efb4d4a46c45.png)
The countdown to the broadcast begins but abnormally stops after the countdown ends and the only interactable thing on the broadcast menu is the stop broadcast button, nothing shows up on discord or on my screen to indicate that streaming has started, if it has started at all.

**Comment by toastylol** [comment]
ps: this is on iPad, as far as I've seen, iPhone users face the same issue too.

**Comment by localip** [comment]
This is due to the bundle id's conflicting. Enmity will never be able to screenshare unless installed with TrollStore or proper entitlements which require an Enterprise or Developer certificate to work.

Once uninstalling the conflicting bundle id (Enmity in this case), you should be able to screenshare on your vanilla Discord app.
