### ISSUE TITLE
Is switching to the old UI possible?

### ISSUE THREAD

**Issue by Seeka49** [enmity-mod/enmity#78]
the main reason i downloaded this, cant find it anywhere in the app, is it possible?

**Comment by i-hate-discord-servers** [comment]
From the discord server, in general chat of all places, since the devs want you to join a different server for every little thing you want to know instead of just having a public forum or wiki people can visit without needing an account
I’ve also swapped out the discord message links to the links those links link to

## Want to get rid of the new user interface?
### Here's how:

1. Install Enmity. You can read [this](https://github.com/enmity-mod/enmity/blob/main/docs/install.md) to discover how.
2. Once you have successfully installed Enmity, you are required to install the EnableStaging plugin from [here](https://github.com/acquitelol/EnableStaging/tree/mistress)
3. Once installed, if you go to your Discord settings and scroll to the bottom you should find an **Experiments** tab. If you don't, restart your app.
4. Search for **Tabs V2 - redesign opt out for T2** and set it to **Treatment 1**
5. Search for **Tabs V2 - redesign opt-out/in for all** and set it to **Not Eligible**
6. Exit the Experiments tab, and scroll up to the **Appearance** tab.
7. Look for a setting called **Show New Layout** and disable it.
8. Profit.

### Notes:
- Discord may remove this experiment at **ANY** time.
- The old user interface is now considered **legacy**. This means it will *never* receive any further updates, including bug fixes.

## Enjoy!
